export const RADIO_SIM_SCENARIOS = [
  {
    id: 'faa-kfxe-vfr-departure-sim',
    title: 'Towered VFR Departure',
    subtitle: 'Ramp to departure handoff',
    region: 'FAA',
    scenarioType: 'Ground + Takeoff',
    airport: 'KFXE',
    airportName: 'Fort Lauderdale Executive',
    aircraftType: 'fixed-wing',
    aircraftLabel: 'Cessna 172S',
    callsign: 'Cessna 4723A',
    tailNumber: 'N4723A',
    weather: 'VFR · 10SM · SCT025',
    traffic: 'Moderate',
    difficulty: 'Student',
    intro: 'You are parked at Banyan ramp with information Alpha. Request a VFR westbound departure, taxi to runway 09, and depart after tower clearance.',
    map: {
      viewBox: '0 0 1000 620',
      runway: {
        x: 116,
        y: 154,
        width: 768,
        height: 92,
        label: 'RWY 09 / 27',
      },
      taxiways: [
        { id: 'alpha', d: 'M180 405 L180 292 L500 292 L500 246', label: 'A' },
        { id: 'hold', d: 'M500 292 L500 246', label: 'HS' },
        { id: 'departure', d: 'M500 200 L816 200', label: 'DEP' },
      ],
      ramps: [
        { x: 92, y: 384, width: 176, height: 112, label: 'Banyan Ramp' },
        { x: 724, y: 374, width: 164, height: 94, label: 'East Ramp' },
      ],
      points: {
        ramp: { x: 180, y: 438, heading: -90, label: 'Ramp' },
        taxiA: { x: 180, y: 292, heading: 0, label: 'Taxiway A' },
        holdShort: { x: 500, y: 292, heading: -90, label: 'Hold short 09' },
        runway: { x: 500, y: 200, heading: 90, label: 'Runway 09' },
        airborne: { x: 820, y: 200, heading: 90, label: 'Departure' },
      },
    },
    setup: {
      scenarioTypes: ['Ground + Takeoff', 'Approach', 'Emergency'],
      airports: ['KFXE', 'KOPF', 'KMIA'],
      aircraft: ['Cessna 172S', 'Piper Archer', 'Bell 206B3'],
      weather: ['VFR · 10SM · SCT025', 'MVFR · 5SM · BKN018', 'IFR · 2SM · OVC006'],
      traffic: ['Light', 'Moderate', 'Busy'],
      complexity: ['Student', 'Private', 'Commercial'],
    },
    exchanges: [
      {
        id: 'say-request',
        phase: 'Ramp',
        frequency: '121.75',
        controller: 'Executive Ground',
        controllerLine: 'Cessna 4723A, Executive Ground, say request.',
        pilotPrompt: 'Request taxi for a VFR westbound departure.',
        transmitLabel: 'Taxi request',
        aircraftPoint: 'ramp',
        route: [],
        expectedMaxWords: 24,
        required: [
          { label: 'controller', terms: ['executive ground', 'ground'] },
          { label: 'callsign', terms: ['cessna 4723a', 'n4723a', '4723a'] },
          { label: 'position', terms: ['banyan ramp', 'ramp'] },
          { label: 'request', terms: ['taxi', 'vfr departure', 'westbound', 'to the west'] },
          { label: 'atis', terms: ['information alpha', 'alpha'] },
        ],
        ideal: 'Executive Ground, Cessna 4723A at Banyan ramp, VFR departure to the west with information Alpha.',
        nextControllerLine: 'Cessna 4723A, runway 09, taxi via Alpha. Hold short runway 09.',
        nextPoint: 'taxiA',
        coach: 'The request should include controller, callsign, position, departure request, and ATIS.',
      },
      {
        id: 'taxi-readback',
        phase: 'Taxi',
        frequency: '121.75',
        controller: 'Executive Ground',
        controllerLine: 'Cessna 4723A, runway 09, taxi via Alpha. Hold short runway 09.',
        pilotPrompt: 'Read back the runway, taxi route, hold-short instruction, and callsign.',
        transmitLabel: 'Taxi readback',
        aircraftPoint: 'taxiA',
        route: ['alpha'],
        expectedMaxWords: 16,
        required: [
          { label: 'runway', terms: ['runway 09', 'runway 9', 'zero niner'] },
          { label: 'route', terms: ['alpha'] },
          { label: 'hold short', terms: ['hold short'] },
          { label: 'callsign', terms: ['cessna 4723a', 'n4723a', '4723a'] },
        ],
        ideal: 'Runway 09 via Alpha, hold short runway 09, Cessna 4723A.',
        nextControllerLine: 'Cessna 4723A, readback correct. Monitor tower 120.9 approaching runway 09.',
        nextPoint: 'holdShort',
        coach: 'Hold-short instructions are mandatory readback items. Keep the callsign at the end.',
      },
      {
        id: 'tower-ready',
        phase: 'Hold Short',
        frequency: '120.90',
        controller: 'Executive Tower',
        controllerLine: 'Cessna 4723A, Executive Tower, continue holding short runway 09. Traffic departing prior to you.',
        pilotPrompt: 'Advise tower you are holding short and ready for departure.',
        transmitLabel: 'Ready call',
        aircraftPoint: 'holdShort',
        route: ['alpha', 'hold'],
        expectedMaxWords: 16,
        required: [
          { label: 'tower', terms: ['executive tower', 'tower'] },
          { label: 'callsign', terms: ['cessna 4723a', 'n4723a', '4723a'] },
          { label: 'location', terms: ['holding short runway 09', 'hold short runway 09', 'short runway 09'] },
          { label: 'ready', terms: ['ready for departure', 'ready to depart', 'ready'] },
        ],
        ideal: 'Executive Tower, Cessna 4723A holding short runway 09, ready for departure.',
        nextControllerLine: 'Cessna 4723A, runway 09 cleared for takeoff. Fly runway heading.',
        nextPoint: 'runway',
        coach: 'Tower wants who you are, where you are, and what you need.',
      },
      {
        id: 'takeoff-readback',
        phase: 'Takeoff',
        frequency: '120.90',
        controller: 'Executive Tower',
        controllerLine: 'Cessna 4723A, runway 09 cleared for takeoff. Fly runway heading.',
        pilotPrompt: 'Read back the takeoff clearance and assigned heading.',
        transmitLabel: 'Takeoff readback',
        aircraftPoint: 'runway',
        route: ['departure'],
        expectedMaxWords: 14,
        required: [
          { label: 'clearance', terms: ['cleared for takeoff'] },
          { label: 'runway', terms: ['runway 09', 'runway 9', 'zero niner'] },
          { label: 'heading', terms: ['runway heading'] },
          { label: 'callsign', terms: ['cessna 4723a', 'n4723a', '4723a'] },
        ],
        ideal: 'Runway 09 cleared for takeoff, runway heading, Cessna 4723A.',
        nextControllerLine: 'Cessna 4723A, contact departure 119.45. Good day.',
        nextPoint: 'airborne',
        coach: 'Read back the runway, takeoff clearance, heading restriction, and callsign.',
      },
      {
        id: 'departure-handoff',
        phase: 'Departure',
        frequency: '119.45',
        controller: 'Departure',
        controllerLine: 'Cessna 4723A, contact departure 119.45. Good day.',
        pilotPrompt: 'Acknowledge the frequency change.',
        transmitLabel: 'Handoff',
        aircraftPoint: 'airborne',
        route: ['departure'],
        expectedMaxWords: 10,
        required: [
          { label: 'frequency', terms: ['119.45', '119 45', 'one one niner four five'] },
          { label: 'callsign', terms: ['cessna 4723a', 'n4723a', '4723a'] },
        ],
        ideal: 'Over to departure 119.45, Cessna 4723A.',
        nextControllerLine: 'Frequency change approved.',
        nextPoint: 'airborne',
        coach: 'Frequency changes can be brief, but the new frequency and callsign should be clear.',
      },
    ],
  },
]
