// FAA AIRAC chart cycle. Updates every 28 days. Single source of truth for
// every d-tpp URL and the bundled chart index; bump this one string per cycle.
export const FAA_CHART_CYCLE = '2606'
export const FAA_DTPP_BASE = `https://aeronav.faa.gov/d-tpp/${FAA_CHART_CYCLE}/`

export const FAA_AIRPORTS = [
  // US: Major hubs
  { icao:'KATL', name:'Hartsfield-Jackson Atlanta Intl',  city:'Atlanta, GA' },
  { icao:'KLAX', name:'Los Angeles Intl',                  city:'Los Angeles, CA' },
  { icao:'KORD', name:"O'Hare Intl",                       city:'Chicago, IL' },
  { icao:'KDFW', name:'Dallas/Fort Worth Intl',            city:'Dallas, TX' },
  { icao:'KDEN', name:'Denver Intl',                       city:'Denver, CO' },
  { icao:'KJFK', name:'John F. Kennedy Intl',              city:'New York, NY' },
  { icao:'KSFO', name:'San Francisco Intl',                city:'San Francisco, CA' },
  { icao:'KLAS', name:'Harry Reid Intl',                   city:'Las Vegas, NV' },
  { icao:'KPHX', name:'Phoenix Sky Harbor Intl',           city:'Phoenix, AZ' },
  { icao:'KIAH', name:'George Bush Intercontinental',      city:'Houston, TX' },
  { icao:'KMIA', name:'Miami Intl',                        city:'Miami, FL' },
  { icao:'KSEA', name:'Seattle-Tacoma Intl',               city:'Seattle, WA' },
  { icao:'KBOS', name:'Logan Intl',                        city:'Boston, MA' },
  { icao:'KCLT', name:'Charlotte Douglas Intl',            city:'Charlotte, NC' },
  { icao:'KEWR', name:'Newark Liberty Intl',               city:'Newark, NJ' },
  { icao:'KSAN', name:'San Diego Intl',                    city:'San Diego, CA' },
  { icao:'KMSP', name:'Minneapolis-Saint Paul Intl',       city:'Minneapolis, MN' },
  { icao:'KDTW', name:'Detroit Metropolitan Wayne Co',     city:'Detroit, MI' },
  { icao:'KPHL', name:'Philadelphia Intl',                 city:'Philadelphia, PA' },
  { icao:'KLGA', name:'LaGuardia',                         city:'New York, NY' },
  { icao:'KBWI', name:'Baltimore/Washington Intl',         city:'Baltimore, MD' },
  { icao:'KSLC', name:'Salt Lake City Intl',               city:'Salt Lake City, UT' },
  { icao:'KIAD', name:'Washington Dulles Intl',            city:'Washington, DC' },
  { icao:'KDCA', name:'Ronald Reagan Washington Natl',     city:'Washington, DC' },
  { icao:'KMCO', name:'Orlando Intl',                      city:'Orlando, FL' },
  { icao:'KMDW', name:'Chicago Midway Intl',               city:'Chicago, IL' },
  { icao:'KHOU', name:'William P. Hobby',                  city:'Houston, TX' },
  { icao:'KAUS', name:'Austin-Bergstrom Intl',             city:'Austin, TX' },
  { icao:'KPDX', name:'Portland Intl',                     city:'Portland, OR' },
  { icao:'KFLL', name:'Fort Lauderdale-Hollywood Intl',   city:'Fort Lauderdale, FL' },
  { icao:'KRDU', name:'Raleigh-Durham Intl',               city:'Raleigh, NC' },
  { icao:'KSTL', name:'St. Louis Lambert Intl',            city:'St. Louis, MO' },
  { icao:'KPIT', name:'Pittsburgh Intl',                   city:'Pittsburgh, PA' },
  { icao:'KCVG', name:'Cincinnati/Northern Kentucky Intl', city:'Cincinnati, OH' },
  { icao:'KCLE', name:'Cleveland Hopkins Intl',            city:'Cleveland, OH' },
  { icao:'KMEM', name:'Memphis Intl',                      city:'Memphis, TN' },
  { icao:'KBNA', name:'Nashville Intl',                    city:'Nashville, TN' },
  { icao:'KSAT', name:'San Antonio Intl',                  city:'San Antonio, TX' },
  { icao:'KTPA', name:'Tampa Intl',                        city:'Tampa, FL' },
  { icao:'KMSY', name:'Louis Armstrong New Orleans Intl',  city:'New Orleans, LA' },
  { icao:'KPBI', name:'Palm Beach Intl',                   city:'West Palm Beach, FL' },
  { icao:'KRSW', name:'Southwest Florida Intl',            city:'Fort Myers, FL' },
  { icao:'KJAX', name:'Jacksonville Intl',                 city:'Jacksonville, FL' },
  { icao:'KBUF', name:'Buffalo Niagara Intl',              city:'Buffalo, NY' },
  { icao:'KOKE', name:'Oke City Will Rogers World',        city:'Oklahoma City, OK' },
  { icao:'KTUL', name:'Tulsa Intl',                        city:'Tulsa, OK' },
  { icao:'KABQ', name:'Albuquerque Intl Sunport',          city:'Albuquerque, NM' },
  { icao:'KTUS', name:'Tucson Intl',                       city:'Tucson, AZ' },
  { icao:'KBHM', name:'Birmingham-Shuttlesworth Intl',    city:'Birmingham, AL' },
  { icao:'KMKE', name:'Milwaukee Mitchell Intl',           city:'Milwaukee, WI' },
  { icao:'KIND', name:'Indianapolis Intl',                 city:'Indianapolis, IN' },
  { icao:'KCMH', name:'John Glenn Columbus Intl',          city:'Columbus, OH' },
  { icao:'KDSM', name:'Des Moines Intl',                   city:'Des Moines, IA' },
  { icao:'KCHS', name:'Charleston Intl',                   city:'Charleston, SC' },
  { icao:'KSAV', name:'Savannah/Hilton Head Intl',         city:'Savannah, GA' },
  { icao:'KTYS', name:'McGhee Tyson',                      city:'Knoxville, TN' },
  { icao:'KGRR', name:'Gerald R. Ford Intl',               city:'Grand Rapids, MI' },
  { icao:'KRIC', name:'Richmond Intl',                     city:'Richmond, VA' },
  { icao:'KSDF', name:'Louisville Intl - Standiford Field',city:'Louisville, KY' },
  { icao:'KELP', name:'El Paso Intl',                      city:'El Paso, TX' },
  { icao:'KOAK', name:'Oakland Intl',                      city:'Oakland, CA' },
  { icao:'KSJC', name:'Norman Y. Mineta San Jose Intl',   city:'San Jose, CA' },
  { icao:'KSMF', name:'Sacramento Intl',                   city:'Sacramento, CA' },
  { icao:'KSNA', name:'John Wayne - Orange County',        city:'Santa Ana, CA' },
  { icao:'KBUR', name:'Hollywood Burbank',                 city:'Burbank, CA' },
  { icao:'KONT', name:'Ontario Intl',                      city:'Ontario, CA' },
  { icao:'KRNO', name:'Reno-Tahoe Intl',                   city:'Reno, NV' },
  { icao:'KANC', name:'Ted Stevens Anchorage Intl',        city:'Anchorage, AK' },
  { icao:'PHNL', name:'Daniel K. Inouye Intl',             city:'Honolulu, HI' },
  // Canada
  { icao:'CYYZ', name:'Toronto Pearson Intl',              city:'Toronto, ON' },
  { icao:'CYVR', name:'Vancouver Intl',                    city:'Vancouver, BC' },
  { icao:'CYUL', name:'Montréal-Trudeau Intl',             city:'Montréal, QC' },
  { icao:'CYYC', name:'Calgary Intl',                      city:'Calgary, AB' },
  { icao:'CYEG', name:'Edmonton Intl',                     city:'Edmonton, AB' },
  { icao:'CYWG', name:'Winnipeg James Armstrong Richardson Intl', city:'Winnipeg, MB' },
  // Central America / Caribbean
  { icao:'MSLP', name:'El Salvador Intl',                  city:'San Salvador, SV' },
  { icao:'MSSS', name:'Ilopango Intl',                     city:'San Salvador, SV' },
  { icao:'MMMX', name:'Benito Juárez Intl',                city:'Mexico City, MX' },
  { icao:'MMUN', name:'Cancún Intl',                       city:'Cancún, MX' },
  { icao:'MMGL', name:'Don Miguel Hidalgo y Costilla Intl',city:'Guadalajara, MX' },
  { icao:'MMTJ', name:'Tijuana Intl. Gen Abelardo L Rodriguez', city:'Tijuana, MX' },
  { icao:'MGGT', name:'La Aurora Intl',                    city:'Guatemala City, GT' },
  { icao:'MHTG', name:'Toncontín Intl',                    city:'Tegucigalpa, HN' },
  { icao:'MNMG', name:'Augusto C. Sandino Intl',           city:'Managua, NI' },
  { icao:'MROC', name:'Juan Santamaría Intl',              city:'San José, CR' },
  { icao:'MPTO', name:'Tocumen Intl',                      city:'Panama City, PA' },
  { icao:'MBPV', name:'Providenciales Intl',               city:'Providenciales, TC' },
  { icao:'MKJP', name:'Norman Manley Intl',                city:'Kingston, JM' },
  { icao:'TNCM', name:'Princess Juliana Intl',             city:'Sint Maarten' },
  { icao:'MDSD', name:'Las Américas Intl',                 city:'Santo Domingo, DO' },
  { icao:'TJSJ', name:'Luis Muñoz Marín Intl',             city:'San Juan, PR' },
  { icao:'MUBА', name:'José Martí Intl',                   city:'Havana, CU' },
]
